modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="icon.png"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="cobblemon"
    type="required"
    reason="Cobblemon integration for villager shop and interactions"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="cobbledollars"
    type="required"
    reason="CobbleDollars currency integration for villager shop"
    ordering="AFTER"
    side="BOTH"
